# Generated by Django 3.1.3 on 2021-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycontrol', '0002_auto_20211009_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_of_close',
            field=models.DateField(blank=True, null=True),
        ),
    ]
