# Generated by Django 3.1.3 on 2021-10-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycontrol', '0004_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
