# Generated by Django 3.1.3 on 2021-11-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easycontrol', '0006_filereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cash_register_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easycontrol.cashregister'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='forgot', max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easycontrol.user'),
        ),
    ]
